FileVersion = 1
Dependencies = {corlib = "*", RSDKv5 = "*"}

[Project]
Name = "RSDK-Game"
StartupObject = "what.Program"
DefaultNamespace = "what"
ProcessorMacros = ["RETRO_REV02", "RETRO_REV0U"]

[Configs.Debug.Win64]
PostBuildCmds = ["CopyToDependents(\"$(ProjectDir)/dist/*.dll\")"]
PreprocessorMacros = ["DEBUG", "RETRO_REV0U", "RETRO_REV02"]

[[ProjectFolder.Items]]
Type = "IgnoreFolder"
Name = "Objects"
AutoInclude = true
